config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :find_flat, only: [:show, :edit, :update, :destroy]

  def index
    @flats = Flat.all
  end

  def show

  end

  def find_flat
    @flat = Flat.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<div class='container'>
  <h1>All our Flats</h1>
  <h4>All <%= @flats.length %> Flats</h1>
  <div class='row'>
    <% @flats.each do |flat| %>
      <div class="col-4">
        <div  class='card my-4'>
          <%= image_tag "https://i.picsum.photos/id/83#{flat.id}/300/200.jpg", alt: "alttext" %>
          <div class='card-design px-4 pt-4'>
            <div class=' middle-card'>
              <h5> <%= flat.name %></h5>
              <%= flat.address %>
            </div>
            <div class = 'pt-4 d-flex justify-content-between'>
              <p><i class="fas fa-euro-sign"></i> <%= flat.price_per_night %></p>
              <p><i class="fas fa-user-friends "></i> <%= flat.number_of_guests %></p>
            </div>
          </div>
          <div class='border-top border-black p-2 justify-content-center d-flex'>
              <%= link_to flat_path(flat), class:"text-primary mr-2" do %>
                More Info
              <% end %>
              <a class="text-warning mr-2">Edit </a>
              <a class="text-danger">Remove </a>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/flats/show.html.erb
<div class='image-top-flat'></div>
<h1> <%= @flat.name %> </h1>

<p> <%= @flat.description %></p>

<p> <%= @flat.price_per_night %>€</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <%= render 'shared/navbarr' %>
    <%= yield %>
  </body>
</html>

app/views/shared/_navbarr.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light d-flex justify-content-between">
  <div>
    <a class="navbar-brand" href="#">Simple Airbnb</a>
  </div>
  <div>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse space" id="navbarSupportedContent">
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0 mr-2" type="submit">Search</button>
        <button class="btn btn-outline-primary my-2 my-sm-0" type="submit">Add Flat</button>
      </form>
    </div>
  </div>
</nav>